### ISSUE TITLE
SIF file question

### ISSUE THREAD

**Issue by kdunn926** [DKopala/MicrowaveChamber#1]
Hello,

Thank you for providing this example file. I saw the webinar you did based on this Elmer definition and was wondering if you could provide some additional references for how you derived these constants (similar to what you have in the presentation for the others):

https://github.com/DKopala/MicrowaveChamber/blob/008e48ecfa6c5f550af86c47e7b44047fc5d8806/mic_chamber_case.sif#L29-L31

**Comment by DKopala** [comment]
Hello,

Thank you for your interest in the code. Phase constants are strictly related to Helmholtz equation (being a part of a wave propagation constant) and for each case, depending on both waveguide's shape and wave type, they have to be calculated differently. I will soon provide formulas and more detailed description of the project regarding to your message. As you have noticed, there are some gaps in the webinar that need to be filled. Thank you very much for your suggestion.

**Comment by kdunn926** [comment]
Hi @DKopala - I saw your new commits with the derivations. Thank you again for proving all these resources here!
